config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations"}

  root to: 'home#home'

  resources :users
  resources :posts
  resources :closed_posts
  resources :conversations, only: [:index, :show, :destroy, :new, :create] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end
  post 'conversations/create' => 'conversations#create' #ask aaron if there's a cleaner way to do this...
  resources :comments
  resources :favorite_post
  resources :venmo
  
  resources :reviews, only: [:new, :create]

  get '/about' => 'home#about'

  get '/send_message' => 'home#send_message'

  get '/inbox' => 'home#inbox'
  
  get 'post_new' => 'posts#new'
  
  get 'posts' => 'posts#index'
  
  get 'post' => 'posts#show'
    
  delete 'post' => 'posts#destroy'

  get 'restore_post' => 'closed_posts#restore'

  get 'favorites' => 'posts#fav_index'

  put 'favorite' => 'posts#favorite'

  get 'venmo_authorize' => 'venmo#callback'

  get 'venmo_initialize_payment' => 'venmo#initialize_payment'

  get 'venmo_final_payment' => 'venmo#final_payment'

  get 'users/new'
  get 'home/login'
  get 'home/signup'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post

	validates :text, presence: true
	validates :user_id, numericality: true, presence: true
	validates :post_id, numericality: true, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!

	def new
        @comment = Comment.new
    end

	def create
	  @comment = Comment.new(comment_params)
    @post = Post.find(params[:post_id])
	  @comment.user_id = current_user.id
	  @comment.post_id = @post.id
	  current_user.comments << @comment
	  @post.comments << @comment

    if @comment.save
  	  redirect_to comments_path(:post_id => @post.id)
    else
      render 'new'
    end
	end

    def index
      if Post.where(:id => params[:post_id]).empty?
          redirect_to posts_path
      else
          @comments = Comment.all.where(:post_id => params[:post_id])
      end
    end

    def edit
        @comment = Comment.find(params[:id])
        if current_user.id != @comment.user_id
          redirect_to comments_path(:post_id => @comment.post_id)
        end
    end

    def update
        @comment = Comment.find(params[:id])
        @post = Post.find(@comment.post_id)
        if @comment.update_attributes(comment_params)
          redirect_to comments_path(:post_id => @post.id)
        else
          render 'edit'
        end
    end

    def destroy
      @comment = Comment.find(params[:id])
      if current_user.id != @comment.user_id
          redirect_to comments_path(:post_id => @comment.post_id)
      else
          Comment.destroy(params[:id])
          redirect_to comments_path(:post_id => @comment.post_id)
      end
    end

    private
      	def comment_params
      		  params.require(:comment).permit(:user_id, :post_id, :text)
      	end
    
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/edit.html.erb
<!DOCTYPE html>
<% provide(:title, 'Updating Comment') %>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Newsfeed</title>

    <!-- Bootstrap Core CSS -->
    <link href="../../css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="../../css/newsfeed/newsfeed.css" rel="stylesheet">
    <link href="../../css/update/update.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Raleway">
        <!-- jQuery -->
    <script src="../../js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="../../js/bootstrap.min.js"></script>

</head>
    <!-- Navigation -->
  <nav class="navbar-color navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">Oskimart</a>
          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                  <li>
                      <a href="/about">About</a>
                  </li>
                  <li class = "dropdown">
                      <a class = "dropdown-toggle" id="Categories" data-toggle="dropdown" role="button">
                      	Categories <b class="caret"></b>
                      </a>
					  <ul class="dropdown-menu">
					    <li><%=link_to "Books", posts_path(category_id: 'Books'), :id => "Books" %></li>
					    <li><%=link_to "Technology", posts_path(category_id: 'Technology'), :id => "Technology" %></li>
					   	<li><%=link_to "Furniture", posts_path(category_id: 'Furniture'), :id => "Furniture" %></li>
					    <li><%=link_to "Service", posts_path(category_id: 'Service'), :id => "Service" %></li>
					    <li><%=link_to "Other", posts_path(category_id: 'Other'), :id => "Other" %></li>
					  </ul>						
                  </li>

                  <li>
                    <li><%=link_to "Favorites", posts_path(favorites: true)%></li> 
                    <li><%=link_to "Conversations", conversations_path%></li>
                  </li>
              </ul>
              <ul class="nav navbar-nav navbar-right">

                  <%if user_signed_in? %>
              			<li id= 'profile'>
            					<%=link_to user_path(current_user.id), :id => 'profile' do%>
            						<%=User.find(current_user.id).first_name%>
            						<span class="glyphicon glyphicon-user"></span> 
            					<%end%>
              			</li>
              			<li>
              				
              				<%=link_to destroy_user_session_path, :method=>'delete', :id => 'Logout' do%>
              					Logout
              					<span class="glyphicon glyphicon-log-out"></span> 
              				<%end%>
              					
              			</li>

              		<% else %>
              			<li>
              				<%=link_to new_user_session_path do%>
              					Login
              					<span class="glyphicon glyphicon-log-in"></span> 
              				<% end %>
              			</li>
              		<%end%>

              </ul>
          </div>
      </div>
  </nav>

<h1 class = "col-md-offset-1 col-xs-offset-1"> Updating Comment </h1>
<div class = "container updated-post top-buffer-25 bottom-padding-30">
	<div class="row top-buffer-25">
		<div class='col-md-6 col-md-offset-3 col-xs-8 col-xs-offset-2'>
			<%= form_for(@comment, :method => :put, url: comment_path) do |f| %>

		        <%= render 'shared/comment_errors' %>
			  	<div class = "row ">
					<%= f.label :text %>				
					<%= f.text_field :text, class: 'form-control' %>

				</div>

				<div class = "row top-buffer-25">
					<div class="col-md-offset-3 col-md-3">
							<%= f.submit "Update", class: "btn btn-primary", id: "Update" %>
					</div>
          <div class="col-md-3">
          <%= link_to 'Back', comments_path(:post_id => @comment.post_id), class: "back-button", id: "Back" %>
        </div>
				</div>	
			<% end %>
		</div>
	</div>
</div>
</html>

app/views/comments/index.html.erb
<!DOCTYPE html>
<% provide(:title, Post.find(params[:post_id]).title) %>
    <html lang="en">

    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <!-- Bootstrap Core CSS -->
        <link href="css/bootstrap.min.css" rel="stylesheet">

        <!-- Custom CSS -->
        <link href="css/newsfeed/newsfeed.css" rel="stylesheet"> <!-- Lucas's css file -->
        <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Raleway">
        <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
            <!-- jQuery -->
        <script src="js/jquery.js"></script>

        <!-- Bootstrap Core JavaScript -->
        <script src="js/bootstrap.min.js"></script>


    </head>

    <body>

        <!-- Navigation -->
        <nav class="navbar-color navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/posts">Oskimart</a>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="/about">About</a>
                        </li>
                        <li class = "dropdown">
                            <a class = "dropdown-toggle" id="Categories" data-toggle="dropdown" role="button">
                              Categories <b class="caret"></b>
                            </a>
                          <ul class="dropdown-menu">
                            <li><%=link_to "General", posts_path(), :id => "General" %></li>
                            <li><%=link_to "Books", posts_path(category_id: 'Books'), :id => "Books" %></li>
                            <li><%=link_to "Technology", posts_path(category_id: 'Technology'), :id => "Technology" %></li>
                            <li><%=link_to "Furniture", posts_path(category_id: 'Furniture'), :id => "Furniture" %></li>
                            <li><%=link_to "Service", posts_path(category_id: 'Service'), :id => "Service" %></li>
                            <li><%=link_to "Other", posts_path(category_id: 'Other'), :id => "Other" %></li>


                          </ul>
                              
                        </li>

                        
                        <li><%=link_to "Favorites", posts_path(favorites: true)%></li> 
                        <li><%=link_to "Conversations", conversations_path%></li>

                        


                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <%if user_signed_in? %>
                          <li id= 'profile'>
                            <%=link_to user_path(current_user.id), :id => 'profile' do%>
                              <%=User.find(current_user.id).first_name%>
                              <span class="glyphicon glyphicon-user"></span> 
                            <%end%>
                          </li>
                          <li>
                            
                            <%=link_to destroy_user_session_path, :method=>'delete', :id => 'Logout' do%>
                              Logout
                              <span class="glyphicon glyphicon-log-out"></span> 
                            <%end%>
                              
                          </li>

                        <% else %>
                          <li>
                            <%=link_to new_user_session_path do%>
                              Login
                              <span class="glyphicon glyphicon-log-in"></span> 
                            <% end %>
                          </li>
                        <%end%>

                    </ul>
                </div>
            </div>
        </nav>

    <div class = "overlay"></div>
    <div class = "container top-buffer-35">
        <div class = "row">
             <h1 class = "newsfeed-title"> Post View </h1> 
        </div>

        <div class = "row top-buffer-35 newsfeed-post">
            <% post = Post.find(params[:post_id]) %>
            <h2 class = "post-title">Title: <%= post.title%></h2>
            <div class = "col-md-4">
                <%= image_tag post.image_url(:thumb) %>
            </div>
            <div class = "col-md-7 col-md-offset-1">
                <div class = "row post-description top-buffer-25">
                  Description: <%= post.description %>
                </div>
                <div class = "row top-buffer-25">
                    <div class = "col-md-3">
                      Category: <%= post.category %>
                    </div>

                    <div class = "col-md-3 col-md-offset-1"> Price: <%= post.price %> </div>
                    <div class = "col-md-3 col-md-offset-1"> Posted By: <%=link_to User.find(post.user_id).first_name, user_path(post.user_id)%>
                    </div>

                </div>
              <div class = "row top-buffer-25">
                    <% if current_user.id == post.user_id %>
                        <%= link_to "Update", edit_post_path(post), class: "post-option-button", :id => "Update" %>
                        <%= link_to "Close", post, method: :delete, data: { confirm: "Are you sure?" }, class: "post-option-button", :id => "Close" %>
                    <% end %>

                    
                    <%= link_to "Comments", comments_path(:post_id => post.id), class: "post-option-button", :id => "Comments" %>
                    <%= link_to "Favorite" , favorite_path(:post_id => post.id),class: "post-option-button", method: :put, :id => "Favorite" %>
                </div>


            </div>
        </div>
        <div class = "row top-buffer-25">
            <div class="col-md-offset-4 col-md-3">
                <%= link_to "Add Comment", new_comment_path(:post_id => params[:post_id]), class: "btn btn-lg btn-primary", id: "Add Comment" %>
            </div>
            <div class="col-md-3">
              <%= link_to 'Back', posts_path, class: "btn btn-lg btn-primary", id: "Back" %>
            </div>
          </div>
        </div>


          <div class = "container top-buffer-25 bottom-buffer-50">
            <% @comments.each do |comment| %>
                <h2 class = "post-title"></h2>
            <div class = "row top-buffer-35 newsfeed-post" style = "background-color: #5F8FF5">
                <h2 class = "post-title"></h2>
                <div class = "col-md-7 col-md-offset-1">
                    <div class = "row post-description top-buffer-25">
                      Comment: <%= comment.text %>
                    </div>
                    <div class = "row top-buffer-25">
                        <div class = "col-md-3 "> 
                          Posted By: <%= User.find(comment.user_id).first_name %> 
                        </div>
                        <div class = "col-md-6">
                          <% if current_user.id == comment.user_id %>
                            <%= link_to "Update", edit_comment_path(comment), class: "post-option-button", id: "Update_comment" %>
                            <%= link_to "Remove", comment, method: :delete, data: { confirm: "Are you sure?" }, class: "post-option-button", id: "Remove_comment" %></td>
                          <% end %>
                        </div>
                    </div>

                </div>
              </div>

        <% end %>
      </div>

      
    </div>


    </body>
</html>

app/views/comments/new.html.erb
<!DOCTYPE html>
<% provide(:title, 'Add comments for ' + Post.find(params[:post_id]).title) %>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Newsfeed</title>

    <!-- Bootstrap Core CSS -->
    <link href="../../css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="../../css/newsfeed/newsfeed.css" rel="stylesheet">
    <link href="../../css/update/update.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Raleway">
        <!-- jQuery -->
    <script src="../../js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="../../js/bootstrap.min.js"></script>

</head>
    <!-- Navigation -->
  <nav class="navbar-color navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">Oskimart</a>
          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                  <li>
                      <a href="/about">About</a>
                  </li>
                  <li class = "dropdown">
                      <a class = "dropdown-toggle" id="Categories" data-toggle="dropdown" role="button">
                      	Categories <b class="caret"></b>
                      </a>
        					  <ul class="dropdown-menu">
        					    <li><%=link_to "Books", posts_path(category_id: 'Books'), :id => "Books" %></li>
        					    <li><%=link_to "Technology", posts_path(category_id: 'Technology'), :id => "Technology" %></li>
        					   	<li><%=link_to "Furniture", posts_path(category_id: 'Furniture'), :id => "Furniture" %></li>
        					    <li><%=link_to "Service", posts_path(category_id: 'Service'), :id => "Service" %></li>
        					    <li><%=link_to "Other", posts_path(category_id: 'Other'), :id => "Other" %></li>
        					  </ul>
                  </li>
                  <li>
                    <li><%=link_to "Favorites", posts_path(favorites: true)%></li> 
                    <li><%=link_to "Conversations", conversations_path%></li>
                  </li>
              </ul>
              <ul class="nav navbar-nav navbar-right">

                  <%if user_signed_in? %>
              			<li id= 'profile'>
            					<%=link_to user_path(current_user.id), :id => 'profile' do%>
            						<%=User.find(current_user.id).first_name%>
            						<span class="glyphicon glyphicon-user"></span> 
            					<%end%>
              			</li>
              			<li>
              				
              				<%=link_to destroy_user_session_path, :method=>'delete', :id => 'Logout' do%>
              					Logout
              					<span class="glyphicon glyphicon-log-out"></span> 
              				<%end%>
              					
              			</li>

              		<% else %>
              			<li>
              				<%=link_to new_user_session_path do%>
              					Login
              					<span class="glyphicon glyphicon-log-in"></span> 
              				<% end %>
              			</li>
              		<%end%>

              </ul>
          </div>
      </div>
  </nav>
<div class = "overlay"></div>

<div class = "container updated-post top-buffer-25 bottom-padding-30">
  <h1 class = "col-md-offset-1 col-xs-offset-1"> Adding Comment </h1>
	<div class="row top-buffer-25">
		<div class='col-md-6 col-md-offset-3 col-xs-8 col-xs-offset-2'>
			<%= form_for(:comment, :method => :post, url: comments_path(:post_id => params[:post_id])) do |f| %>
		        <%= render 'shared/comment_errors' %>
			  	<div class = "row ">
					<%= f.label :text %>				
					<%= f.text_field :text, class: 'form-control' %>

				</div>


				<div class = "row top-buffer-25">
					<div class="col-md-offset-3 col-md-3">
							<%= f.submit "Comment", class: "btn btn-primary" %>
							
					</div>

					<div class="col-md-3">
						<%= link_to 'Back', comments_path(:post_id => params[:post_id]), class: "back-button", id: "Back" %>
						
					</div>
				</div>	
			<% end %>
		</div>
	</div>
</div>
</html>