config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations"}

  root to: 'home#home'

  resources :users
  resources :posts
  resources :closed_posts
  resources :conversations, only: [:index, :show, :destroy, :new, :create] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end
  post 'conversations/create' => 'conversations#create' #ask aaron if there's a cleaner way to do this...
  resources :comments
  resources :favorite_post
  resources :venmo
  
  resources :reviews, only: [:new, :create]

  get '/about' => 'home#about'

  get '/send_message' => 'home#send_message'

  get '/inbox' => 'home#inbox'
  
  get 'post_new' => 'posts#new'
  
  get 'posts' => 'posts#index'
  
  get 'post' => 'posts#show'
    
  delete 'post' => 'posts#destroy'

  get 'restore_post' => 'closed_posts#restore'

  get 'favorites' => 'posts#fav_index'

  put 'favorite' => 'posts#favorite'

  get 'venmo_authorize' => 'venmo#callback'

  get 'venmo_initialize_payment' => 'venmo#initialize_payment'

  get 'venmo_final_payment' => 'venmo#final_payment'

  get 'users/new'
  get 'home/login'
  get 'home/signup'

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  # this manages a single conversation thread
  before_action :authenticate_user!
  before_action :get_mailbox, except: [:new, :create]
  before_action :get_conversation, except: [:index, :empty_trash, :new, :create]
  before_action :get_box, only: [:index]

  def new
    @chosen_recipient = User.find_by(id: params[:to].to_i).where.not(id: current_user.id) if params[:to]
  end

  def create
    recipients = User.where(id: params['recipients'])
    if recipients.empty?
      flash[:warning] = "There's no one to message to!"
      redirect_to new_conversation_path
    elsif recipients.include?(current_user)
      flash[:warning] = "Go outside. Make some friends. Talking to yourself isn't the answer."
      redirect_to new_conversation_path
    else
      conversation = current_user.send_message(recipients, params[:message][:body], params[:message][:subject]).conversation
      redirect_to conversation_path(conversation)
    end
  end

  def index
    if @box.eql? "inbox"
      @conversations = @mailbox.inbox
    elsif @box.eql? "sent"
      @conversations = @mailbox.sentbox
    else
      @conversations = @mailbox.trash
    end
    @conversations = @conversations.paginate(page: params[:page], per_page: 10)
  end

  def show
    @conversation.mark_as_read(current_user)
  end

  def reply
    current_user.reply_to_conversation(@conversation, params[:body])
    @conversation.recipients.each do |recipient|
      recipient.untrash(@conversation)
    end
    redirect_to conversation_path(@conversation)
  end

  # 3 methods below: request/response usage unclear. We possibly want to refactor these to respond to ajax calls
  # also note: these methods are purely experimental at this moment. No tests have been written for them
  # USE AT YOUR OWN RISK!
  def destroy
    @conversation.move_to_trash(current_user)
    redirect_to conversations_path
  end

  def restore
    @conversation.untrash(current_user)
    redirect_to conversations_path
  end

  def empty_trash
    @mailbox.trash.each do |conversation|
      conversation.mark_as_deleted(current_user)
    end
    redirect_to conversations_path
  end

  private

  def get_mailbox
    @mailbox ||= current_user.mailbox
  end

  def get_conversation
    @conversation ||= @mailbox.conversations.find(params[:id])
  end

  def get_box
    if params[:box].blank? or !["inbox","sent","trash"].include?(params[:box])
      params[:box] = 'inbox'
    end
    @box = params[:box]
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper

  def mailbox_section(title, current_box, opts = {})
    opts[:class] = opts.fetch(:class, '')
    opts[:class] += ' active' if title.downcase == current_box
    content_tag :li, link_to(title.capitalize, conversations_path(box: title.downcase)), opts
  end

  def recipients_options(chosen_recipient = nil)
    s = ''
    User.where.not(id: current_user.id).each do |user|
      s << "<option value='#{user.id}' data-img-src='#{gravatar_image_url(user.email, size: 50)}' #{'selected' if user == chosen_recipient}>#{user.first_name + ' ' + user.last_name}</option>"
      #s << "<option value='#{user.id}'>#{user.name}</option>"
    end
    s.html_safe
  end

  def participants(participants = [])
    s = ''
    participants.delete(current_user)
    participants.each do |participant|
      s += participant.full_name + ", "
    end
    s = s[0..s.length-3]
    s.html_safe
  end
end

app/views/conversations/_conversation.html.erb
<li class="list-group-item clearfix top-buffer-50">
  <h1>Subject: <%= link_to conversation.subject, conversation_path(conversation), id: conversation.subject %></h1>

  <div class="btn-group-vertical pull-right">
    <% if conversation.is_trashed?(current_user) %>
      <%= link_to 'Restore', restore_conversation_path(conversation), id: 'Restore',class: 'btn btn-xs btn-info', method: :post %>
    <% else %>
      <%= link_to 'Move to trash', conversation_path(conversation), id: 'Move to trash', class: 'btn btn-xs btn-danger', method: :delete,
                  data: {confirm: 'Are you sure?'} %>
    <% end %>
  </div>

  <p style = "padding-left:15px">Participants: <%= render 'conversations/participants', conversation: conversation %>
  </p>
  <div class = "row left-buffer-30 top-buffer-25" style = "border-top: solid #E3E3E3 1px; padding-top: 10px">
    <h4>Last Message:</h4>
    <div class = "last-message" style = "padding-left:20px">
      <div class = "last-message">
        <%= conversation.last_message.sender.full_name %>: <%= conversation.last_message.body %>

      </div>
      <small>
        
        (<span class="text-muted"><%= conversation.last_message.created_at %></span>)
      </small>
    </div>

  </div> 
  <p>
</p>
</li>

app/views/conversations/_participants.html.erb
<%= participants(conversation.participants) %>

app/views/conversations/index.html.erb
<!DOCTYPE html>
<% provide(:title, 'Conversations') %>

    <html lang="en">

    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>Inbox</title>

        <!-- Bootstrap Core CSS -->
        <link href="css/bootstrap.min.css" rel="stylesheet">

        <!-- Custom CSS -->
        <link href="css/newsfeed/newsfeed.css" rel="stylesheet"> <!-- Lucas's css file -->
        <link href="css/messaging/inbox.css" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Raleway">
        <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
            <!-- jQuery -->
        <script src="js/jquery.js"></script>
        <script src="js/newsfeed/newsfeed.js"></script>

        <!-- Bootstrap Core JavaScript -->
        <script src="js/bootstrap.min.js"></script>


    </head>

    <body>

        <!-- Navigation -->
      <nav class="navbar-color navbar navbar-inverse navbar-fixed-top" role="navigation">
          <div class="container">
              <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                      <span class="sr-only">Toggle navigation</span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                  </button>
                  <a class="navbar-brand" href="/posts">Oskimart</a>
              </div>
              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                  <ul class="nav navbar-nav">
                      <li>
                          <a href="/about">About</a>
                      </li>
                      <li class = "dropdown">
                          <a class = "dropdown-toggle" id="Categories" data-toggle="dropdown" role="button">
                            Categories <b class="caret"></b>
                          </a>
                <ul class="dropdown-menu">
                  <li><%=link_to "General", posts_path(), :id => "General" %></li>
                  <li><%=link_to "Books", posts_path(category_id: 'Books'), :id => "Books" %></li>
                  <li><%=link_to "Technology", posts_path(category_id: 'Technology'), :id => "Technology" %></li>
                  <li><%=link_to "Furniture", posts_path(category_id: 'Furniture'), :id => "Furniture" %></li>
                  <li><%=link_to "Service", posts_path(category_id: 'Service'), :id => "Service" %></li>
                  <li><%=link_to "Other", posts_path(category_id: 'Other'), :id => "Other" %></li>
                </ul>
                            
                      </li>
                      <li><%=link_to "Favorites", posts_path(favorites: true)%></li> 
                    <li><%=link_to "Conversations", conversations_path%></li>
                  </ul>
                  <ul class="nav navbar-nav navbar-right">

                      <%if user_signed_in? %>
                        <li id= 'profile'>
                          <%=link_to user_path(current_user.id), :id => 'profile' do%>
                            <%=User.find(current_user.id).first_name%>
                            <span class="glyphicon glyphicon-user"></span> 
                          <%end%>
                        </li>
                        <li>
                          
                          <%=link_to destroy_user_session_path, :method=>'delete', :id => 'Logout' do%>
                            Logout
                            <span class="glyphicon glyphicon-log-out"></span> 
                          <%end%>
                            
                        </li>

                      <% else %>
                        <li>
                          <%=link_to new_user_session_path do%>
                            Login
                            <span class="glyphicon glyphicon-log-in"></span> 
                          <% end %>
                        </li>
                      <%end%>

                  </ul>
              </div>
          </div>
      </nav>


  <div class = "container">
    <div class = "page-header">
      <h1>Your Conversations</h1>

    </div>
    <div class = "col-md-3 top-buffer-15">
      <ul class="nav nav-pills nav-stacked">
        <%= mailbox_section 'inbox', @box, :id => 'Inbox' %>
        <%= mailbox_section 'sent', @box, :id => 'Sent' %>
        <%= mailbox_section 'trash', @box, :id => 'Trash' %>
      </ul>

      <ul class = "top-buffer-200 shift-left-40">
        <div>
          <%= link_to 'Start conversation', new_conversation_path, class: 'btn btn-lg btn-primary', id: 'Start conversation' %>
        </div>

        <% if @box == 'trash' %>
          <div class="top-buffer-25">
            <%= link_to 'Empty trash', empty_trash_conversations_path, id: 'Empty trash', class: 'btn btn-danger', method: :delete,
                           data: {confirm: 'Are you sure?'} %>
          </div>
        <% end %>
      </ul>
    </div>

    <div class = "col-md-8 col-md-offset-1">
      <ul class="list-group">
        <%= render partial: 'conversations/conversation', collection: @conversations %>
      </ul>

    <%= will_paginate @conversations %>
    <!--
        <div class = "row conversation-row top-buffer-15">
            <div class = "row left-buffer-30">
                <div class = "conversation-subject">Dummy Subject</div>
            </div>

            <div class = "row left-buffer-30">

              <div class = "posted-to">Sent To: Eric Zhou</div>
            </div>
            <div class = "row left-buffer-30 top-buffer-25">
              <div class = "last-message">
                <div class = "last-message">
                  Last message of this conversation Last message of this conversation
                </div>
              </div>

            </div> 
        </div>
        <div class = "row conversation-row">
            <div class = "row left-buffer-30">
                <div class = "conversation-subject">Dummy Subject</div>
            </div>

            <div class = "row left-buffer-30">

              <div class = "posted-to">Sent: Eric Zhou</div>
            </div>
            <div class = "row left-buffer-30 top-buffer-25">
              <div class = "last-message">
                <div class = "last-message">
                  Last message of this conversation Last message of this conversation
                </div>
              </div>

            </div> 
        </div>

          <div class = "row conversation-row">
            <div class = "row left-buffer-30">
                <div class = "conversation-subject">Dummy Subject</div>
            </div>

            <div class = "row left-buffer-30">

              <div class = "posted-to">Sent To: Eric Zhou</div>
            </div>
            <div class = "row left-buffer-30 top-buffer-25">
              <div class = "last-message">
                <div class = "last-message">
                  Last message of this conversation Last message of this conversation
                </div>
              </div>

            </div> 
        -->
        </div>
      
        
    </div>


  </div>


  </body>
</html>




  <div class="col-sm-9">


  </div>
</div>

app/views/conversations/new.html.erb
<!DOCTYPE html>
<% provide(:title, 'New Conversation') %>

    <html lang="en">

    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>Inbox</title>

        <!-- Bootstrap Core CSS -->
        <link href="../css/bootstrap.min.css" rel="stylesheet">

        <!-- Custom CSS -->
        <link href="../css/newsfeed/newsfeed.css" rel="stylesheet"> <!-- Lucas's css file -->
        <link href="../css/messaging/inbox.css" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Raleway">
        <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
            <!-- jQuery -->
        <script src="../js/jquery.js"></script>
        <script src="../js/newsfeed/newsfeed.js"></script>

        <!-- Bootstrap Core JavaScript -->
        <script src="../js/bootstrap.min.js"></script>


    </head>

    <body>

        <!-- Navigation -->
      <nav class="navbar-color navbar navbar-inverse navbar-fixed-top" role="navigation">
          <div class="container">
              <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                      <span class="sr-only">Toggle navigation</span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                  </button>
                  <a class="navbar-brand" href="/posts">Oskimart</a>
              </div>
              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                  <ul class="nav navbar-nav">
                      <li>
                          <a href="/about">About</a>
                      </li>
                      <li class = "dropdown">
                          <a class = "dropdown-toggle" id="Categories" data-toggle="dropdown" role="button">
                            Categories <b class="caret"></b>
                          </a>
                <ul class="dropdown-menu">
                  <li><%=link_to "General", posts_path(), :id => "General" %></li>
                  <li><%=link_to "Books", posts_path(category_id: 'Books'), :id => "Books" %></li>
                  <li><%=link_to "Technology", posts_path(category_id: 'Technology'), :id => "Technology" %></li>
                  <li><%=link_to "Furniture", posts_path(category_id: 'Furniture'), :id => "Furniture" %></li>
                  <li><%=link_to "Service", posts_path(category_id: 'Service'), :id => "Service" %></li>
                  <li><%=link_to "Other", posts_path(category_id: 'Other'), :id => "Other" %></li>
                </ul>
                            
                      </li>
                      <li><%=link_to "Favorites", posts_path(favorites: true)%></li> 
                    <li><%=link_to "Conversations", conversations_path%></li>
                  </ul>
                  <ul class="nav navbar-nav navbar-right">

                      <%if user_signed_in? %>
                        <li id= 'profile'>
                          <%=link_to user_path(current_user.id), :id => 'profile' do%>
                            <%=User.find(current_user.id).first_name%>
                            <span class="glyphicon glyphicon-user"></span> 
                          <%end%>
                        </li>
                        <li>
                          
                          <%=link_to destroy_user_session_path, :method=>'delete', :id => 'Logout' do%>
                            Logout
                            <span class="glyphicon glyphicon-log-out"></span> 
                          <%end%>
                            
                        </li>

                      <% else %>
                        <li>
                          <%=link_to new_user_session_path do%>
                            Login
                            <span class="glyphicon glyphicon-log-in"></span> 
                          <% end %>
                        </li>
                      <%end%>

                  </ul>
              </div>
          </div>
      </nav>
      <div class = "container">
          <div class = "page-header">
            <h1>New Conversation</h1>

          </div>
      </div>
      <div class = "container" style = "padding-top: 20px">

          <div class = "col-md-10 col-md-offset-1">
            <%= form_tag conversations_create_path, method: :post do %>
              <div class="form-group">
                <%= label_tag 'message[subject]', 'Subject' %>
                <%= text_field_tag 'message[subject]', nil, class: 'form-control', required: true %>
              </div>

              <div class="form-group">
                <%= label_tag 'message[body]', 'Message' %>
                <%= text_area_tag 'message[body]', nil, rows:8, class: 'form-control', required: true %>
              </div>

              <div class="form-group">
                <%= label_tag 'recipients', 'Choose recipients' %>
                <%= select_tag 'recipients', recipients_options(@chosen_recipient), multiple: true, class: 'form-control chosen-it' %>
              </div>

              <%= submit_tag 'Send', class: 'btn btn-primary' %>
            <% end %>
          </div>
      </div>
  </body>
</html>

app/views/conversations/show.html.erb
<!DOCTYPE html>
<% provide(:title, 'Current Conversation') %>

    <html lang="en">

    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>Inbox</title>

        <!-- Bootstrap Core CSS -->
        <link href="../css/bootstrap.min.css" rel="stylesheet">

        <!-- Custom CSS -->
        <link href="../css/newsfeed/newsfeed.css" rel="stylesheet"> <!-- Lucas's css file -->
        <link href="../css/messaging/inbox.css" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Raleway">
        <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
            <!-- jQuery -->
        <script src="../js/jquery.js"></script>
        <script src="../js/newsfeed/newsfeed.js"></script>

        <!-- Bootstrap Core JavaScript -->
        <script src="../js/bootstrap.min.js"></script>


    </head>

    <body>

        <!-- Navigation -->
      <nav class="navbar-color navbar navbar-inverse navbar-fixed-top" role="navigation">
          <div class="container">
              <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                      <span class="sr-only">Toggle navigation</span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                  </button>
                  <a class="navbar-brand" href="/posts">Oskimart</a>
              </div>
              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                  <ul class="nav navbar-nav">
                      <li>
                          <a href="/about">About</a>
                      </li>
                      <li class = "dropdown">
                          <a class = "dropdown-toggle" id="Categories" data-toggle="dropdown" role="button">
                            Categories <b class="caret"></b>
                          </a>
                <ul class="dropdown-menu">
                  <li><%=link_to "General", posts_path(), :id => "General" %></li>
                  <li><%=link_to "Books", posts_path(category_id: 'Books'), :id => "Books" %></li>
                  <li><%=link_to "Technology", posts_path(category_id: 'Technology'), :id => "Technology" %></li>
                  <li><%=link_to "Furniture", posts_path(category_id: 'Furniture'), :id => "Furniture" %></li>
                  <li><%=link_to "Service", posts_path(category_id: 'Service'), :id => "Service" %></li>
                  <li><%=link_to "Other", posts_path(category_id: 'Other'), :id => "Other" %></li>
                </ul>
                            
                      </li>
                      <li><%=link_to "Favorites", posts_path(favorites: true)%></li> 
                    <li><%=link_to "Conversations", conversations_path%></li>
                  </ul>
                  <ul class="nav navbar-nav navbar-right">

                      <%if user_signed_in? %>
                        <li id= 'profile'>
                          <%=link_to user_path(current_user.id), :id => 'profile' do%>
                            <%=User.find(current_user.id).first_name%>
                            <span class="glyphicon glyphicon-user"></span> 
                          <%end%>
                        </li>
                        <li>
                          
                          <%=link_to destroy_user_session_path, :method=>'delete', :id => 'Logout' do%>
                            Logout
                            <span class="glyphicon glyphicon-log-out"></span> 
                          <%end%>
                            
                        </li>

                      <% else %>
                        <li>
                          <%=link_to new_user_session_path do%>
                            Login
                            <span class="glyphicon glyphicon-log-in"></span> 
                          <% end %>
                        </li>
                      <%end%>

                  </ul>
              </div>
          </div>
      </nav>
      <div class = "container">
          <div class = "page-header">
            <h1>Current Conversation</h1>

          </div>
          <div>
              Chatting with
                <%= render 'conversations/participants', conversation: @conversation %>
          </div>
          

          <div class="panel panel-default top-buffer-25">
            <div class="panel-heading">Subject: <%= @conversation.subject %></div>

            <div class="panel-body">
              <div class="messages">
                <% @conversation.receipts_for(current_user).each do |receipt| %>
                  <div class="media">
                    <% message = receipt.message %>
                    <div class="media-body">
                      <h6 class="media-heading"><%= message.sender.first_name %>
                        says at <%= message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></h6>
                      <%= message.body %>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>

          <%= form_tag reply_conversation_path(@conversation), method: :post do %>
            <div class="form-group">
              <%= text_area_tag 'body', nil, cols: 3, class: 'form-control', placeholder: 'Type something...', required: true %>
            </div>
            <%= submit_tag "Send Message", class: 'btn btn-primary' %>
            <%= link_to "Back", conversations_path, class: 'btn btn-primary', id: 'Back' %>

          <% end %>
      </div>
  </body>
</html>