config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations"}

  root to: 'home#home'

  resources :users
  resources :posts
  resources :closed_posts
  resources :conversations, only: [:index, :show, :destroy, :new, :create] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end
  post 'conversations/create' => 'conversations#create' #ask aaron if there's a cleaner way to do this...
  resources :comments
  resources :favorite_post
  resources :venmo
  
  resources :reviews, only: [:new, :create]

  get '/about' => 'home#about'

  get '/send_message' => 'home#send_message'

  get '/inbox' => 'home#inbox'
  
  get 'post_new' => 'posts#new'
  
  get 'posts' => 'posts#index'
  
  get 'post' => 'posts#show'
    
  delete 'post' => 'posts#destroy'

  get 'restore_post' => 'closed_posts#restore'

  get 'favorites' => 'posts#fav_index'

  put 'favorite' => 'posts#favorite'

  get 'venmo_authorize' => 'venmo#callback'

  get 'venmo_initialize_payment' => 'venmo#initialize_payment'

  get 'venmo_final_payment' => 'venmo#final_payment'

  get 'users/new'
  get 'home/login'
  get 'home/signup'

end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


	has_many :posts, dependent: :destroy
	has_many :closed_posts, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :reviews, dependent: :destroy


	# favorite projects implementation 
	has_many :favorite_posts
	has_many :favorites, through: :favorite_posts, source: :post
	mount_uploader :image, ProfilepicUploader

	#Valid sign up fields presence as well as email format.
	before_save { self.email = email.downcase }
	validates :first_name, presence: true
  	validates :last_name, presence: true
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@berkeley+\.edu+\z/i
	validates :email, format: { with: VALID_EMAIL_REGEX, message: "must be Berkeley email!" }
	validates :password, length: {minimum: 8}, on: :create

	#mailboxer mcMagicSauce
	acts_as_messageable

	def full_name
		first_name + ' ' + last_name
	end

	def mailboxer_email(object)
		email
	end






end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!


  def show
  	@user = User.find(params[:id])
    @posts = @user.posts
    @comments = @user.comments
    @reviews = @user.reviews
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update_attributes(user_params)
  		redirect_to @user
    else
      flash[:danger] = "Not a valid image link/file"
      redirect_to @user
  	end
  end

  private
	def user_params
		params.require(:user).permit(:first_name, :last_name, :email, :encrypted_password, :image, :remote_image_url)
	end
  
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.first_name, class: "gravatar")
	end
end

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Viewing post</title>

    <!-- Bootstrap Core CSS -->
    <link href="../../css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="../../css/newsfeed/newsfeed.css" rel="stylesheet">
    <link href="../../css/update/update.css" rel="stylesheet">
    <link href="../../css/show/show.css" rel="stylesheet">
    <link href="../../css/show_user/show-user.css" rel="stylesheet">
    <script src="../../js/show/show.js"></script>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Raleway">
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
        <!-- jQuery -->
    <script src="../../js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="../../js/bootstrap.min.js"></script>

</head>
    <nav class="navbar-color navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/posts">Oskimart</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="/about">About</a>
                    </li>
                    <li class = "dropdown">
                        <a class = "dropdown-toggle" id="Categories" data-toggle="dropdown" role="button">
                          Categories <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                          <li><%=link_to "General", posts_path(), :id => "General" %></li>
                          <li><%=link_to "Books", posts_path(category_id: 'Books'), :id => "Books" %></li>
                          <li><%=link_to "Technology", posts_path(category_id: 'Technology'), :id => "Technology" %></li>
                          <li><%=link_to "Furniture", posts_path(category_id: 'Furniture'), :id => "Furniture" %></li>
                          <li><%=link_to "Service", posts_path(category_id: 'Service'), :id => "Service" %></li>
                          <li><%=link_to "Other", posts_path(category_id: 'Other'), :id => "Other" %></li>
                        </ul>
                          
                    </li>

                    <li><%=link_to "Favorites", posts_path(favorites: true)%></li> 
                    <li><%=link_to "Conversations", conversations_path%></li>
                  
                </ul>
                <ul class="nav navbar-nav navbar-right">

                    <%if user_signed_in? %>
                      <li id= 'profile'>
                        <%=link_to user_path(current_user.id), :id => 'profile' do%>
                          <%=User.find(current_user.id).first_name%>
                          <span class="glyphicon glyphicon-user"></span> 
                        <%end%>
                      </li>
                      <li>
                        
                        <%=link_to destroy_user_session_path, :method=>'delete', :id => 'Logout' do%>
                          Logout
                          <span class="glyphicon glyphicon-log-out"></span> 
                        <%end%>
                          
                      </li>

                    <% else %>
                      <li>
                        <%=link_to new_user_session_path do%>
                          Login
                          <span class="glyphicon glyphicon-log-in"></span> 
                        <% end %>
                      </li>
                    <%end%>

                </ul>
            </div>
        </div>
    </nav>
<div class="container">
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>
<%= yield %>
</div>
<div class = "overlay"></div>
<% provide(:title, @user.first_name) %>

<div class = "container top-buffer-25 text-center">
  <div class = "col-md-4">
    
        <div class = "row col-sm-offset-1">
            <%= image_tag @user.image_url(:thumb), :class=>"img-responsive"%>
        </div>

        <div class="row">
             <h2>Hi, I'm <%= @user.first_name %></h2>  
        </div>
        <div class = "row shift-up-10">
           <%= @user.email %>
        </div>
        <% if @user.id == current_user.id %>
            <div class = "row top-buffer-25">
                <%= form_for @user do |f| %>
                  <div class = "row">
                    <div class = "col-md-offset-4 col-xs-offset-4">
                      <%= f.file_field :image, accept: 'image/png,image/gif,image/jpeg' %>
                    </div>
                    <div class = "col-md-8 col-md-offset-2">
                      <%= f.text_field :remote_image_url, placeholder:"Or enter image url", class:"form-control top-buffer-15" %>
                    </div>
                  </div>
                  <div><%= f.submit "Update Image", class:"top-buffer-25 update-button" %></div>
                <%end%>

            </div>

      <%end%>
      <div class="top-buffer-25">
        <%= link_to "Message", conversations_path, id: 'Message' %>
      </div>
      <div class="top-buffer-25">
        <%= link_to "Closed posts", closed_posts_path(:user_id => @user.id), id: 'Closed posts' %>
      </div>
  </div>
  <div class = "col-md-7 col-md-offset-1 top-buffer-75">
        <div class = "row top-buffer-75">
          <h2>Payment</h2>
        </div>

        <% if current_user.id == @user.id %>
          <%= link_to "Venmo Access Change", "https://api.venmo.com/v1/oauth/authorize?client_id=3195&scope=make_payments%20access_profile%20access_email%20access_phone%20access_balance&response_type=code" %>

        <% else %>
          <% if @user.venmo_id.nil? or current_user.venmo_id.nil? %>
            Please message this person for payment! 
          <% else %>
            <%= link_to "Make a payment via venmo", venmo_initialize_payment_path(receiver: @user.id) %>
          <% end %>
        <% end %>
        <% if current_user.id != @user.id %>
          <div class = "row text-center top-buffer-50">
            <%= link_to "Add Review", new_review_path(:user_id => @user.id), class: "btn btn-lg btn-primary", id: "Add Review" %>
          </div>
        <% end %>
        
          <% if Review.all.where(:user_id => @user.id).count == 0 %>
            <h2>No reviews to show</h2>
          <% else %>
          <h2 class = "top-buffer-25">Reviews:</h2>
          <% Review.all.where(:user_id => @user.id).each do |review| %>
              <div class = "row review top-buffer-25">
                  <div class = "row">
                    <h3>Score: <%= review.score %> </h3>
                  </div>
                  <div class = "row">
                    <h5 class = "text-left" style="line-height:150%"><%= review.feedback %></h5>
                  </div>
              </div>
            <% end %>
          <% end %>


    

  </div>


</div>




  <div class = "container text-center top-buffer-25">

  </div>

<!-- >>>>>>> 369bddd527d0c49be15869ea96648ee4986e8dbe
 -->


</html>

app/views/users/update.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Newsfeed</title>

    <!-- Bootstrap Core CSS -->
    <link href="../../css/bootstrap.min.css" rel="stylesheet">
    <link href="../../css/simple-sidebar.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="../../css/newsfeed/newsfeed.css" rel="stylesheet">
    <link href="../../css/update/update.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Raleway">
        <!-- jQuery -->
    <script src="../../js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="../../js/bootstrap.min.js"></script>

</head>
    <!-- Navigation -->
  <nav class="navbar-color navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">Oskimart</a>
          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                  <li>
                      <a href="/about">About</a>
                  </li>
                  <li class = "dropdown">
                      <a class = "dropdown-toggle" data-toggle="dropdown" role="button">
                      	Categories <b class="caret"></b>
                      </a>
					  <ul class="dropdown-menu">
					    <li><%=link_to "Books", posts_path(category_id: 'Books')%></li>
					    <li><%=link_to "Technology", posts_path(category_id: 'Technology')%></li>
					   	<li><%=link_to "Furniture", posts_path(category_id: 'Furniture')%></li>
					    <li><%=link_to "Service", posts_path(category_id: 'Service')%></li>
					    <li><%=link_to "Other", posts_path(category_id: 'Other')%></li>
					  </ul>
												
                  </li>
              </ul>
              <ul class="nav navbar-nav navbar-right">

                  <%if user_signed_in? %>
              			<li>
            					<%=link_to user_path(current_user.id) do%>
            						<%=User.find(current_user.id).first_name%>
            						<span class="glyphicon glyphicon-user"></span> 
            					<%end%>
              			</li>
              			<li>
              				
              				<%=link_to destroy_user_session_path, :method=>'delete' do%>
              					Logout
              					<span class="glyphicon glyphicon-log-out"></span> 
              				<%end%>
              					
              			</li>

              		<% else %>
              			<li>
              				<%=link_to new_user_session_path do%>
              					Login
              					<span class="glyphicon glyphicon-log-in"></span> 
              				<% end %>
              			</li>
              		<%end%>

              </ul>
          </div>
      </div>
  </nav>
<h1 class = "col-md-offset-1 col-xs-offset-1"> Updating post </h1>
<div class = "container updated-post top-buffer-25 bottom-padding-30">
	<div class="row top-buffer-25">
		<div class='col-md-6 col-md-offset-3 col-xs-8 col-xs-offset-2'>
		    <%= form_for(@user, :method => :put, url: user_path) do |f| %>

		        <%= render 'shared/error_messages' %>
		  

			<div class = "row top-buffer-25">

				<%= f.label :description %>
				<%= f.text_area :description, rows:"7", class: 'form-control description-box' %>

			</div>

		
			<div class = "row top-buffer-25">
				<div class="col-md-offset-3 col-md-3">
						<%= f.submit "Update", class: "update-button" %>
						<% end %>
				</div>
				<div class="col-md-3">
					<%= link_to 'Back', user_path(current_user.id), class: "back-button"%>
					

				</div>
			</div>

			
			

		</div>


		</div>
	</div>
</html>
<!-- the header below was added, not sure if we need this -->
<!-- <h1> Updating profile picture </h1>
 -->