config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations"}

  root to: 'home#home'

  resources :users
  resources :posts
  resources :closed_posts
  resources :conversations, only: [:index, :show, :destroy, :new, :create] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end
  post 'conversations/create' => 'conversations#create' #ask aaron if there's a cleaner way to do this...
  resources :comments
  resources :favorite_post
  resources :venmo
  
  resources :reviews, only: [:new, :create]

  get '/about' => 'home#about'

  get '/send_message' => 'home#send_message'

  get '/inbox' => 'home#inbox'
  
  get 'post_new' => 'posts#new'
  
  get 'posts' => 'posts#index'
  
  get 'post' => 'posts#show'
    
  delete 'post' => 'posts#destroy'

  get 'restore_post' => 'closed_posts#restore'

  get 'favorites' => 'posts#fav_index'

  put 'favorite' => 'posts#favorite'

  get 'venmo_authorize' => 'venmo#callback'

  get 'venmo_initialize_payment' => 'venmo#initialize_payment'

  get 'venmo_final_payment' => 'venmo#final_payment'

  get 'users/new'
  get 'home/login'
  get 'home/signup'

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
  

  # favorited by useres 
  has_many :favorite_posts
  has_many :favorited_by, through: :favorite_posts, source: :user # users that favorite a project
  has_many :comments, dependent: :destroy
  mount_uploader :image, PostspicsUploader

  validates :user_id, presence: true, numericality: true
	validates :title, presence: true
	validates :description, presence: true
	validates :category, presence: true
	validates :price, presence: true
  validates_inclusion_of :category, :in => %w(Books Technology Furniture Service Other), :message => "{{value}} is not a valid category"
  validates_inclusion_of :price, :in => %w($ $$ $$$), :message => "{{value}} is not a valid price"


  def self.filter(price, category_id)
    if category_id.nil? or category_id.empty?
      where(:price => price)
    else
      where(:price => price, :category => category_id)
    end
  end

  def self.favorites(user)
    user.favorites
  end

  def self.search(keywords, category_id, price)
    keyword_regex = "%#{keywords}%"
    if category_id.nil? or category_id.empty?
      if price.nil? or price.empty?
        where("title ILIKE ? or description ILIKE ?", keyword_regex, keyword_regex)
      else
        where("(title ILIKE ? or description ILIKE ?) and price = ?", keyword_regex, keyword_regex, price)
      end 
    else
      if price.nil? or price.empty?
          where("(title ILIKE ? or description ILIKE ?) and category = ?", keyword_regex, keyword_regex, category_id)
      else
          where("(title ILIKE ? or description ILIKE ?) and category = ? and price = ?", keyword_regex, keyword_regex, category_id, price)
      end 
    end

  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token

    def new
        @post = Post.new
    end

    def favorite
      @post = Post.find(params[:post_id])
      # if post in favorite list then remove 
      if current_user.favorites.include?(@post)
        current_user.favorites.delete(@post)
        render json: {favorited: false}
      # add to fav list
      else
        current_user.favorites << @post
        render json: {favorited: true}
      end
    end

    def create
      	@post = Post.new(post_params)
        @post.user_id = current_user.id
        current_user.posts << @post

        if @post.save
          flash[:success] = "Your post has been posted!"
          redirect_to posts_path
        else
          render 'new'
        end
    end

    def show
        @post = Post.find(params[:id])
        @comments = @post.comments
    end

    def index
      if not params[:category_id].nil? and not params[:category_id].empty? 
        @posts = Post.where(:category => params[:category_id]).order('created_at DESC').paginate(page: params[:page], per_page: 5)
        @title =  params[:category_id]
      else
        @posts = Post.all.order('created_at DESC').paginate(page: params[:page], per_page: 5)
        @title = "General"
      end

      if params[:price] #if filter
        if params[:keywords]
          @posts = Post.search(params[:keywords], params[:category_id], params[:price]).order("created_at DESC").paginate(page: params[:page], per_page: 5)
        else
          @posts = Post.filter(params[:price], params[:category_id]).order("created_at DESC").paginate(page: params[:page], per_page: 5)
        end
        @title += ", Price = " + params[:price]
      end 

      if params[:keywords] #if search
        @posts = Post.search(params[:keywords], params[:category_id], params[:price]).order("created_at DESC").paginate(page: params[:page], per_page: 5)
        @title += ", Search = " + params[:keywords]
      end

        if params[:favorites]
          @posts = Post.favorites(current_user).order('created_at DESC').paginate(page: params[:page], per_page: 5)
          @title = "Favorites"
        end
    end

    def edit
        @post = Post.find(params[:id])
        if current_user.id != @post.user_id
          redirect_to posts_path
        end
    end

    def update
        @post = Post.find(params[:id])
        if @post.update_attributes(post_params)
          flash[:success] = "Your post has been updated!"
          redirect_to comments_path(:post_id => @post.id)
        else
          render 'edit'
        end
    end

    def destroy
      @post = Post.find(params[:id])
      if current_user.id != @post.user_id
          redirect_to posts_path
      else
          @closed_post = ClosedPost.create(:user_id => current_user.id, :title => @post.title, :description => @post.description, :category => @post.category, :price => @post.price, :image => @post.image)
          current_user.closed_posts << @closed_post
          Post.destroy(params[:id])
          redirect_to posts_path
      end
    end

    private
      	def post_params
      		  params.require(:post).permit(:user_id, :title, :description, :category, :price, :image, :remote_image_url)
      	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<!DOCTYPE html>
<% provide(:title, 'Update Post ' + @post.title) %>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Newsfeed</title>

    <!-- Bootstrap Core CSS -->
    <link href="../../css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="../../css/newsfeed/newsfeed.css" rel="stylesheet">
    <link href="../../css/update/update.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Raleway">
        <!-- jQuery -->
    <script src="../../js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="../../js/bootstrap.min.js"></script>

</head>
    <!-- Navigation -->
  <nav class="navbar-color navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">Oskimart</a>
          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                  <li>
                      <a href="/about">About</a>
                  </li>
                  <li class = "dropdown">
                      <a class = "dropdown-toggle" id="Categories" data-toggle="dropdown" role="button">
                      	Categories <b class="caret"></b>
                      </a>
					  <ul class="dropdown-menu">
					    <li><%=link_to "Books", posts_path(category_id: 'Books'), :id => "Books" %></li>
					    <li><%=link_to "Technology", posts_path(category_id: 'Technology'), :id => "Technology" %></li>
					   	<li><%=link_to "Furniture", posts_path(category_id: 'Furniture'), :id => "Furniture" %></li>
					    <li><%=link_to "Service", posts_path(category_id: 'Service'), :id => "Service" %></li>
					    <li><%=link_to "Other", posts_path(category_id: 'Other'), :id => "Other" %></li>
					  </ul>
												
                  </li>
                  <li><%=link_to "Favorites", posts_path(favorites: true)%></li> 
                    <li><%=link_to "Conversations", conversations_path%></li>
              </ul>
              <ul class="nav navbar-nav navbar-right">

                  <%if user_signed_in? %>
              			<li id= 'profile'>
            					<%=link_to user_path(current_user.id), :id => 'profile' do%>
            						<%=User.find(current_user.id).first_name%>
            						<span class="glyphicon glyphicon-user"></span> 
            					<%end%>
              			</li>
              			<li>
              				
              				<%=link_to destroy_user_session_path, :method=>'delete', :id => 'Logout' do%>
              					Logout
              					<span class="glyphicon glyphicon-log-out"></span> 
              				<%end%>
              					
              			</li>

              		<% else %>
              			<li>
              				<%=link_to new_user_session_path do%>
              					Login
              					<span class="glyphicon glyphicon-log-in"></span> 
              				<% end %>
              			</li>
              		<%end%>

              </ul>
          </div>
      </div>
  </nav>
<div class = "overlay"></div>

<div class = "container updated-post top-buffer-25 bottom-padding-30">
  <h1 class = "col-md-offset-1 col-xs-offset-1"> Updating post </h1>
	<div class="row top-buffer-25">
		<div class='col-md-6 col-md-offset-3 col-xs-8 col-xs-offset-2'>
		    <%= form_for(@post, :method => :put, url: post_path) do |f| %>

		        <%= render 'shared/post_errors' %>
		  <div class = "row ">
				<%= f.label :title %>
				<%= f.text_field :title, class: 'form-control' %>
			</div>

			<div class = "row top-buffer-25">

				<%= f.label :description %>
				<%= f.text_area :description, rows:"7", class: 'form-control description-box' %>

			</div>
			<div class = "row top-buffer-25">
				<div class = "control-label post_buttons">
					<%= f.label :category %>
					<%= f.select :category, ['Technology', 'Books','Furniture', 'Service', 'Other'], class: 'form-control' %>
				</div>
				<div class = "control-label post_buttons">
					<%= f.label :price%>
					<%= f.select :price, ['$', '$$','$$$'], class: 'form-control' %>
				</div>
        <div class = "control-label post_buttons">
          <%= f.label :image %>
          <%= f.file_field :image, accept: 'image/png,image/gif,image/jpeg' %>
        </div>
        <div class = "col-md-8">
          <%= f.text_field :remote_image_url, placeholder:"Or enter image url", class:"form-control top-buffer-15" %>
        </div>
        <div class = "col-md-4">
          <%= image_tag @post.image_url(:thumb) %>
        </div>
			</div>

			<div class = "row top-buffer-25">
				<div class="col-md-offset-3 col-md-3">
						<%= f.submit "Update", class: "update-button", id: "Update" %>
				<% end %>
		    </div>
				<div class="col-md-3">
					<%= link_to 'Back', posts_path, class: "back-button", id: "Back" %>
				</div>
			</div>

			
			

		</div>


		</div>
	</div>
</html>

app/views/posts/index.html.erb
<!DOCTYPE html>
<% provide(:title, 'Newsfeed') %>
    
    <html lang="en">

    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>Newsfeed</title>

        <!-- Bootstrap Core CSS -->
        <link href="css/bootstrap.min.css" rel="stylesheet">

        <!-- Custom CSS -->
        <link href="css/newsfeed/newsfeed.css" rel="stylesheet"> <!-- Lucas's css file -->
        <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Raleway">
        <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
            <!-- jQuery -->
        <script src="js/jquery.js"></script>
        <script src="js/newsfeed/newsfeed.js"></script>

        <!-- Bootstrap Core JavaScript -->
        <script src="js/bootstrap.min.js"></script>

        <script src="js/newsfeed/favorite.js"></script>


    </head>

    <body>

        <!-- Navigation -->
      <nav class="navbar-color navbar navbar-inverse navbar-fixed-top" role="navigation">
          <div class="container">
              <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                      <span class="sr-only">Toggle navigation</span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                  </button>
                  <a class="navbar-brand" href="/posts">Oskimart</a>
              </div>
              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                  <ul class="nav navbar-nav">
                      <li>
                          <a href="/about">About</a>
                      </li>
                      <li class = "dropdown" id="Categories">
                          <a class = "dropdown-toggle" id="Categories" data-toggle="dropdown" role="button">
                            Categories <b class="caret"></b>
                          </a>
                          <ul class="dropdown-menu">
                            <li><%=link_to "General", posts_path(), :id => "General" %></li>
                            <li><%=link_to "Books", posts_path(category_id: 'Books'), :id => "Books" %></li>
                            <li><%=link_to "Technology", posts_path(category_id: 'Technology'), :id => "Technology" %></li>
                            <li><%=link_to "Furniture", posts_path(category_id: 'Furniture'), :id => "Furniture" %></li>
                            <li><%=link_to "Service", posts_path(category_id: 'Service'), :id => "Service" %></li>
                            <li><%=link_to "Other", posts_path(category_id: 'Other'), :id => "Other" %></li>
                          </ul>
                            
                      </li>
                      
                        <li>
                            <%=link_to "Favorites", posts_path(favorites: true)%>
                        </li>
                        <li>
                            <%=link_to "Conversations", conversations_path%>
                        </li>
                  </ul>

                    <ul class="nav navbar-nav navbar-right">
                        <%if user_signed_in? %>
                    			<li id="profile">
                  					<%=link_to user_path(current_user.id), :id => 'profile' do%>
                  						<%=User.find(current_user.id).first_name%>
                  						<span class="glyphicon glyphicon-user"></span> 
                  					<%end%>
                    			</li>
                    			<li>
                    				
                    				<%=link_to destroy_user_session_path, :method=>'delete', :id => 'Logout' do%>
                    					Logout
                    					<span class="glyphicon glyphicon-log-out"></span> 
                    				<%end%>
                    					
                    			</li>

                    		<% else %>
                    			<li>
                    				<%=link_to new_user_session_path do%>
                    					Login
                    					<span class="glyphicon glyphicon-log-in"></span> 
                    				<% end %>
                    			</li>
                    		<%end%>

                    </ul>
                </div>
            </div>
        </nav>




    </div>
    <div class = "overlay"></div>
    <div class = "container top-buffer-35">

    		<div class = "row">
            <h1 class = "newsfeed-title"><%= @title %></h1> 
    		</div>
        <% if not params[:favorites] %>
        	  <div class = "row top-buffer-25">
          		<div class = "col-md-offset-1  col-xs-offset-1">
        		    <form class="navbar-form">
        		        <%= form_tag(posts_path, :method => "get", id: "search-form") do %>
          		        <%= text_field_tag :keywords, params[:search], placeholder: "Search posts by title or description", :class=>"search-input" %>
                      <%= hidden_field_tag :category_id , params[:category_id] %>
                      <%= hidden_field_tag :price , params[:price] %>

          		        <%= submit_tag "Search", :class=>"search-button"%>
        		        <% end %>
        		    </form>
        		  </div>
        	  </div>

          	<div class = "row top-buffer-25">
          		<div class = "col-md-6 col-md-offset-1 col-xs-8 col-xs-offset-1">
          			<h5>Filter by price:</h5>
        	  		<%= link_to "$", posts_path(price: '$', category_id: params[:category_id], keywords: params[:keywords]), class: "price-button", id: "$" %>
        	  		<%= link_to "$$", posts_path(price: '$$', category_id: params[:category_id], keywords: params[:keywords]), class: "price-button", id: "$$" %>
        	  		<%= link_to "$$$", posts_path(price: '$$$', category_id: params[:category_id], keywords: params[:keywords]), class: "price-button", id: "$$$" %>
        	  	</div>
          		<div class = "col-md-4 col-md-offset-5 col-xs-6 col-xs-offset-7 shift-up-20">
          			<%= link_to "Create Post!", post_new_path, class: "create-button", id: "Create Post!" %>
          		</div>
        <% end %>

              <div class = "col-md-4 col-md-offset-9 col-xs-6 col-xs-offset-7 shift-up-80">
                <%= will_paginate @posts, :class=>"pagination" %>
              </div>
          	</div>
    </div>


    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
    <!-- Container for posts -->
    <div class = "container bottom-buffer-50">
        <% @posts.each do |post| %>

            <div class = "row top-buffer-35 newsfeed-post" data-id="<%=post.id%>">
            		<h2 class = "post-title">Title: <%= post.title%></h2>
		            <div class = "col-md-4">
		            		<!-- <img class="img-responsive" src="http://www.livelifecycling.com/portals/0/Tours/StMaloNice/nice2.jpg" alt=""> -->
                    <%= image_tag post.image_url(:thumb), :class=>"img-responsive" %>
		            </div>
			          <div class = "col-md-7 col-md-offset-1">
			            	<div class = "row post-description top-buffer-25">
			            		Description: <%= post.description %>
			            	</div>
			            	<div class = "row top-buffer-25">
				                <div class = "col-md-3">
				                	Category: <%= post.category %>
				                </div>

				                <div class = "col-md-3 col-md-offset-1"> Price: <%= post.price %> </div>
				                <div class = "col-md-3 col-md-offset-1"> Posted By: <%=link_to User.find(post.user_id).first_name, user_path(post.user_id)%>
                        </div>

			          		</div>
				         	<div class = "row top-buffer-25">

				                <% if current_user.id == post.user_id %>
				                    <%= link_to "Update", edit_post_path(post), class: "post-option-button", id: "Update" %>
				                    <%= link_to "Close", post, method: :delete, data: { confirm: "Are you sure?" }, class: "post-option-button", id: "Close"%>
				                <% end %>

                        
				                <%= link_to "Comments", comments_path(:post_id => post.id), class: "post-option-button", id: "Comments" %>
                        <% if current_user.favorites.include?(post) %>
                            <a class = "unfavorite-button post-option-button" id = "Unfavorite">Unfavorite</a>
                        <% else %>
                            <a class = "favorite-button post-option-button" id = "Favorite">Favorite</a>
                        <% end %>
                           </div>

			          </div>
			                

			        </div>

        <% end %>
      </div>
      <div class = "text-center">
        <%= will_paginate @posts, :class=>"pagination" %>
      </div>
    </div>


    </body>
</html>

app/views/posts/index.js.erb
$(document).ready(function(){
  $(".show-comments").on("click", function() {
    console.log("clicked");
    var modal = $(this).parent().parent().parent().prev();
    console.log(modal);
    modal.fadeIn(500);
    $("div.overlay").fadeIn(300);
  });

  $(".hide-comments").on("click", function() {
    var modal = $(this).parent();
    modal.fadeOut(500);
    $("div.overlay").fadeOut(500);
  })
});

app/views/posts/show.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Viewing post</title>

    <!-- Bootstrap Core CSS -->
    <link href="../../css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="../../css/newsfeed/newsfeed.css" rel="stylesheet">
    <link href="../../css/update/update.css" rel="stylesheet">
    <link href="../../css/show/show.css" rel="stylesheet">
    <script src="../../js/show/show.js"></script>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Raleway">
        <!-- jQuery -->
    <script src="../../js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="../../js/bootstrap.min.js"></script>

</head>
    <nav class="navbar-color navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/posts">Oskimart</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="/about">About</a>
                    </li>
                    <li class = "dropdown">
                        <a class = "dropdown-toggle" id="Categories" data-toggle="dropdown" role="button">
                          Categories <b class="caret"></b>
                        </a>
              <ul class="dropdown-menu">
                <li><%=link_to "General", posts_path(), :id => "General" %></li>
                <li><%=link_to "Books", posts_path(category_id: 'Books'), :id => "Books" %></li>
                <li><%=link_to "Technology", posts_path(category_id: 'Technology'), :id => "Technology" %></li>
                <li><%=link_to "Furniture", posts_path(category_id: 'Furniture'), :id => "Furniture" %></li>
                <li><%=link_to "Service", posts_path(category_id: 'Service'), :id => "Service" %></li>
                <li><%=link_to "Other", posts_path(category_id: 'Other'), :id => "Other" %></li>
              </ul>
                          
                    </li>
                    <li><%=link_to "Favorites", posts_path(favorites: true)%></li> 
                    <li><%=link_to "Conversations", conversations_path%></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">

                    <%if user_signed_in? %>
                      <li id= 'profile'>
                        <%=link_to user_path(current_user.id), :id => 'profile' do%>
                          <%=User.find(current_user.id).first_name%>
                          <span class="glyphicon glyphicon-user"></span> 
                        <%end%>
                      </li>
                      <li>
                        
                        <%=link_to destroy_user_session_path, :method=>'delete', :id => 'Logout' do%>
                          Logout
                          <span class="glyphicon glyphicon-log-out"></span> 
                        <%end%>
                          
                      </li>

                    <% else %>
                      <li>
                        <%=link_to new_user_session_path do%>
                          Login
                          <span class="glyphicon glyphicon-log-in"></span> 
                        <% end %>
                      </li>
                    <%end%>

                </ul>
            </div>
        </div>
    </nav>

    
    <div class = "container">
        <h1>View Post</h1>
            <div class = "row top-buffer-35 newsfeed-post">
                <h2 class = "post-title">Title: <%= @post.title%></h2>

                <div class = "col-md-4">
                    <img class="img-responsive" src="http://www.livelifecycling.com/portals/0/Tours/StMaloNice/nice2.jpg" alt="">
                </div>
                <div class = "col-md-7 col-md-offset-1">
                    <div class = "row post-description top-buffer-25">
                      Description: <%= @post.description %>
                    </div>
                    <div class = "row top-buffer-25">
                      <div class = "col-md-3">
                        Category: <%= @post.category %>
                      </div>

                      <div class = "col-md-3 col-md-offset-1"> Price: <%= @post.price %> </div>
                      <div class = "col-md-3 col-md-offset-1"> Posted By: <%= User.find(@post.user_id).first_name %> </div>
                    </div>
                    <div class = "row top-buffer-25">
                        <% if current_user.id == @post.user_id %>
                            <%= link_to "Edit", edit_post_path(@post), class: "post-option-button"%>
                            <%= link_to "Remove", @post, method: :delete, data: { confirm: "Are you sure?" }, class: "post-option-button" %>
                        <% end %>
                        <a class = "post-option-button show-comments">Show Comments</a>
                  </div>
                  <div>
                    <%= image_tag @post.image_url(:thumb) %>
                  </div>
                </div>
            </div>
    </div>


      <div class = "text-center top-buffer-25">
        <%= link_to '+ New Comment', comments_path(:post_id => @post.id), class:"new-comment-button"%> 
      </div>
      <div class="text-center top-buffer-25">
        <%= link_to 'Back', posts_path, class: "back-button"%>
      </div>
</html>